import 'phaser';

class Test extends Phaser.Scene {
    constructor() {
        super({
            key: 'test'
        })
    }
    preload() {
        this.load.pack('pack', 'assets/pack.json');
    }
    create() {
        var pic = this.add.image(400, 300, 'right')
        //pic.setScale(0.5);
        pic.setDisplaySize(50,50);

// 给定的数据
const data_str = `
Field1
[SCRIPTEVENT]0
 Name=孫文病逝
Condition
 [Turn/=]2
 [FactionExist/=]國民政府
Script
 [PLAYBGM]
 [TEXT]
 民國１３年，在第二次直奉戰爭中獲勝的張作霖和馮玉祥，推
 舉段祺瑞為中華民國臨時執政，並邀南方政府的孫文北上共
 商國事，欲結束中國南北方政府分裂的局面。
 [TX]
 [WAIT]
 [TEXT]
 但孫文於民國１４年一月１日抵達北京後病發，健康急
 轉直下。
 [TX]
 [WAIT]
 [TEXT]
 孫此時已為肝癌末期，全肝堅硬如木。癌細胞四處蔓延，
 無法割治．．．．．．
 [TX]
 [WAIT]
 [TEXT]
 此時，汪精衛和湯爾和對中西醫治療爆發爭論。
 [TX]
 [WAIT]
 [FACE1]
 汪兆銘/汪兆銘
 [SAY1]
 總理經中醫治療後情況有所好轉，應改用中醫！
 [TX]
 [WAIT]
 [FACE2]
 湯爾和/湯爾和
 [SAY2]
 不，中醫不科學，應停用中醫改用西醫！
 [TX]
 [WAIT]
 [FACE1]
 孫文/孫文
 [SAY1]
 ．．．．．．
 [TX]
 [WAIT]
 [FACE2]
 汪兆銘/汪兆銘
 [SAY2]
 總理？總理！
 [TX]
 [WAIT]
 [FACE1]
 湯爾和/湯爾和
 [SAY1]
 孫先生！
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [PICTURE]
 孫文葬禮/孫文葬禮
 [TEXT]
 民國１４年三月１２日，孫中山因肝癌病逝於北京鐵獅子衚衕行轅，年５８歲。
 [TX]
 [WAIT]
 [PICTURE]
 黃埔孫文公祭/黃埔孫文公祭
 [TEXT]
 為革命慘淡奔波半生的孫中山晚年終於得到蘇俄的支援，卻在欲重新起步之時病逝。失去孫中山的國民黨，其聯俄容共的政策將會產生什麼變數呢．．．？
 [TX]
 [WAIT]
 [WAR]
 粵系/國民政府
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]1
 Name=反奉戰爭
Condition
 [Turn/>]9
 [MasterOf/直魯聯軍]奉系
 [FactionExist/=]奉系
 [FactionExist/=]五省聯軍
 [FactionExist/=]國民軍
 [CityOwner/奉系]上海
 [CityOwner/奉系]南京
 [CityOwner/奉系]合肥
Script
 [TEXT]
 民國14年，在二次直奉戰爭中獲勝的張作霖勢力長驅南下，席捲至長江流域一帶。奉系的勢力達到極盛。
 [TX]
 [WAIT]
 [TEXT]
 然而，奉軍如日中天的擴張引起了其它軍閥的不安及不滿。特別是面臨直接威脅的馮玉祥與孫傳芳。
 [TX]
 [WAIT]
 [TEXT]
 孫傳芳連絡長江下游的直系諸將商議共同討奉計畫，此消息被密報給張作霖，但張作霖不以為然。
 [TX]
 [WAIT]
 [FACE2]
 張作霖/張作霖
 [SAY2]
 他媽的！現在全天下只有我打人，絕沒人敢打我！
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 孫傳芳率先出擊，迅速的驅逐了蘇皖的奉軍，並大破前來南下迎擊的張宗昌，俘虜其麾下大將施從濱。
 [TX]
 [WAIT]
 [FACE2]
 孫傳芳/孫傳芳
 [SAY2]
 施將軍，您老不是要來當安徽督辦嗎？這就上任去吧。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 孫傳芳將施從濱處死。
 [TX]
 [WAIT]
 [TEXT]
 另一方面，統帥奉系最精銳部隊的郭松齡，不滿張作霖重用楊宇霆，決心外通馮玉祥反奉。將所部改名東北國民軍，並殺害了不與其共同起事的姜登選。
 [TX]
 [WAIT]
 [FACE1]
 郭松齡/郭松齡
 [SAY1]
 東北的事都叫楊宇霆這幫人弄壞了，安徽、江蘇失敗，斷送了三個師的兵力，現在楊宇霆又纏著老帥，給他們去打地盤子，這個炮頭我不再充當了。要把東北事情辦好，只有把楊宇霆這幫成事不足敗事有餘的傢伙趕走，請少帥來當家。
 [TX]
 [WAIT]
 [PICTURE]
 E001a/東北國民軍
 [FACE1]
 *
 [TEXT]
 郭松齡的部隊一開始勢如破竹的逼近奉天，但在日本的干涉和張學良的不支持下，他的部隊很快就潰散了．．．
 [TX]
 [WAIT]
 [PICTURE]
 郭松齡遺體/遭處死曝屍的郭松齡
 [TEXT]
 隨後，郭松齡夫婦一起被擒獲處死並曝屍。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [TEXT]
 郭松齡的叛變雖然被平定了，但經此役原本形勢大好的奉系元氣大傷，中國的局勢又開始不確定了起來．．．
 [TX]
 [WAIT]
 [WAR]
 國民軍/奉系
 [KILLLEADER]
 施從濱
 [KILLLEADER]
 郭松齡
 [KILLLEADER]
 姜登選
 [ALLWEAKEN]
 奉系
 [CITYOWNER]
 南京/五省聯軍
 [CITYOWNER]
 上海/五省聯軍
 [CITYOWNER]
 合肥/五省聯軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]2
 Name=清黨
Condition
 [FactionExist/=]桂系
 [FactionExist/=]共產黨
 ![CityOwner/直魯聯軍]上海
 ![CityOwner/五省聯軍]上海
 ![CityOwner/奉系]上海
 [FactionCityMore/國民政府]9
Script
 [PLAYBGM]
 [TEXT]
 北伐過程中，中共在敵後煽動工農暴動，使得北伐過程勢如破竹。
 [TX]
 [WAIT]
 [TEXT]
 然而，當這些地方為國民革命軍所攻占後，暴動卻未平息，反而越演越烈。。
 [TX]
 [WAIT]
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 我不幹了，我不幹了．．．
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 總司令，在這種情況下你不幹，責任就能了嗎？
 [TX]
 [WAIT]
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 何應欽也辭職了，他已無法掌握第一軍，你看我怎麼能幹的下去！
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 ．．．．．．
 [TX]
 [WAIT]
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 黨中央已經被共產黨掌握了，軍隊也被共產黨滲透。共產黨控制了工會不停罷工暴動，擾亂生產和治安的恢復。
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 ．．．．．．
 [TX]
 [WAIT]
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 更糟的是，共產黨在農村裡不斷鬥地主，我們的將士在前方打仗，共產黨卻在後方抄他們的家！這仗要怎麼打下去．．．我們的革命就要失敗了！
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 ．．．．．．
 [TX]
 [WAIT]
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 你看怎麼辦？
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 我看只有以快刀斬亂麻的方式清黨，把越軌的左傾幼稚分子鎮壓下去。
 [TX]
 [WAIT]
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 現在如何能談清黨呢！我的軍隊已經靠不住了。
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 那只有一步一步來，我看先把我第七軍一部調到南京附近．．．．．．
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [PICTURE]
 清黨/遭處死的共產黨
 [TEXT]
 於是，蔣中正密令各省一致實行清黨，各地開始對共產黨和左傾分子展開大肆搜殺，而共產黨也以暴動作為回應，兩方相互仇殺報復，局面越來越血腥殘酷．．．．．．
 [TX]
 [WAIT]
 [TEXT]
 國民黨聯俄容共時，史達林曾指示共產黨謂中國國民黨只是一隻檸檬，共產黨人不妨將之一擠再擠，擠乾之後則可信手拋去。此刻看來，國民黨卻先共產黨而擠。
 [TX]
 [WAIT]
 [TEXT]
 由共產國際所催生，接受蘇聯大力援助的國共合作共同歷經了國民黨改組、黃埔建軍、北伐，最後還是走向分道揚鑣的決裂道路。今後兩黨將會各自走向什麼樣的命運呢．．．．．．？
 [TX]
 [WAIT]
 [ALLWEAKEN]
 共產黨
 [WAR]
 國民政府/共產黨
 [REFORM]
 國民政府/Capitalism
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]3
 Name=皇姑屯事件
Condition
 [FactionExist/=]奉系
 ![MasterOf/直魯聯軍]奉系
 [CityNotOwner/奉系]北京
 [CityNotOwner/奉系]保定
 [CityNotOwner/奉系]天津
 [CityNotOwner/奉系]唐山
 [CityOwner/奉系]奉天
 ![FactionCityMore/奉系]10
Script
 [PLAYBGM]
 [TEXT]
 自張作霖在民國１３年第二次直奉戰爭獲勝以來，奉系入關南
 下，掌控中央政府。其勢力甚至直跨長江，彷彿有席捲天下之勢。
 [TX]
 [WAIT]
 [TEXT]
 但僅短短數年間，奉軍損兵折將，喪師失地。
 [TX]
 [WAIT]
 [PLAYBGM]
 [PICTURE]
 皇姑屯事件/被炸毀的火車
 [TEXT]
 面對急轉直下的情勢，張作霖決心退回根據地東北，但卻在回奉天的火車上，和奉系老將吳俊陞一同被炸死。
 [TX]
 [WAIT]
 [TEXT]
 由於日本在此事上的嫌疑最大，甫承父業的張學良決心肅清奉系內的親日派、向來不服他的楊宇霆與常蔭槐。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [TEXT]
 某日楊宇霆與常蔭槐向張學良提出成立東北鐵路督辦公署的要求，張學良推說等晚餐再商議。當夜，張召警務處長率隊將楊宇霆、常蔭槐扣押。
 [TX]
 [WAIT]
 [FACE1]
 張學良/張學良
 [SAY1]
 楊宇霆、常蔭槐吞扣軍餉、貽誤戎機、扶植私人勢力、圖謀不軌、阻撓國家統一，著將處死，即刻執行。
 [TX]
 [WAIT]
 [FACE2]
 楊宇霆/楊宇霆
 [SAY2]
 什麼．．．！？
 [TX]
 [WAIT]
 [TEXT]
 楊宇霆與常蔭槐被張學良槍殺。
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 不論張學良此舉是自毀長城或是先發制人，影響張學良在奉系
 內權威的最後因素已被排除，新一代的東北王誕生了。
 [TX]
 [WAIT]
 [KILLLEADER]
 張作霖
 [KILLLEADER]
 吳俊陞
 [KILLLEADER]
 楊宇霆
 [KILLLEADER]
 常蔭槐
 [GAINUNIT]
 奉系/張學良
 [COMMANDER]
 奉系/張學良
 [PEACEALL]
 奉系
 [NEUTRALITY]
 奉系/22
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]4
 Name=中德合作I
Condition
 [PlayerFaction/=]國民政府
 [FactionPPMore/國民政府]35
 [CityOwner/國民政府]南昌
 [CityOwner/國民政府]贛州
 [CityOwner/國民政府]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 國民政府/-300
 [FREEUPGRADE]
 國民政府/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/國民政府
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]5
 Name=中德合作I（皖系）
Condition
 [PlayerFaction/=]皖系
 [FactionPPMore/皖系]35
 [CityOwner/皖系]南昌
 [CityOwner/皖系]贛州
 [CityOwner/皖系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 皖系/-300
 [FREEUPGRADE]
 皖系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/皖系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]6
 Name=中德合作I（國民軍）
Condition
 [PlayerFaction/=]國民軍
 [FactionPPMore/國民軍]35
 [CityOwner/國民軍]南昌
 [CityOwner/國民軍]贛州
 [CityOwner/國民軍]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 國民軍/-300
 [FREEUPGRADE]
 國民軍/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/國民軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]7
 Name=中德合作I（桂系）
Condition
 [PlayerFaction/=]桂系
 [FactionPPMore/桂系]35
 [CityOwner/桂系]南昌
 [CityOwner/桂系]贛州
 [CityOwner/桂系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 桂系/-300
 [FREEUPGRADE]
 桂系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/桂系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]8
 Name=中德合作I（五省聯軍）
Condition
 [PlayerFaction/=]五省聯軍
 [FactionPPMore/五省聯軍]35
 [CityOwner/五省聯軍]南昌
 [CityOwner/五省聯軍]贛州
 [CityOwner/五省聯軍]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 五省聯軍/-300
 [FREEUPGRADE]
 五省聯軍/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/五省聯軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]9
 Name=中德合作I（川康軍）
Condition
 [PlayerFaction/=]川康軍
 [FactionPPMore/川康軍]35
 [CityOwner/川康軍]南昌
 [CityOwner/川康軍]贛州
 [CityOwner/川康軍]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 川康軍/-300
 [FREEUPGRADE]
 川康軍/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/川康軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]10
 Name=中德合作I（奉系）
Condition
 [PlayerFaction/=]奉系
 [FactionPPMore/奉系]35
 [CityOwner/奉系]南昌
 [CityOwner/奉系]贛州
 [CityOwner/奉系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 奉系/-300
 [FREEUPGRADE]
 奉系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/奉系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]11
 Name=中德合作I（直系）
Condition
 [PlayerFaction/=]直系
 [FactionPPMore/直系]35
 [CityOwner/直系]南昌
 [CityOwner/直系]贛州
 [CityOwner/直系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 直系/-300
 [FREEUPGRADE]
 直系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/直系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]12
 Name=中德合作I（川軍）
Condition
 [PlayerFaction/=]川軍
 [FactionPPMore/川軍]35
 [CityOwner/川軍]南昌
 [CityOwner/川軍]贛州
 [CityOwner/直系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 川軍/-300
 [FREEUPGRADE]
 川軍/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/川軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]13
 Name=中德合作I（滇系）
Condition
 [PlayerFaction/=]滇系
 [FactionPPMore/滇系]35
 [CityOwner/滇系]南昌
 [CityOwner/滇系]贛州
 [CityOwner/滇系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 滇系/-300
 [FREEUPGRADE]
 滇系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/滇系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]14
 Name=中德合作I（黔系）
Condition
 [PlayerFaction/=]黔系
 [FactionPPMore/黔系]35
 [CityOwner/黔系]南昌
 [CityOwner/黔系]贛州
 [CityOwner/黔系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 黔系/-300
 [FREEUPGRADE]
 黔系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/黔系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]15
 Name=中德合作I（晉系）
Condition
 [PlayerFaction/=]晉系
 [FactionPPMore/晉系]35
 [CityOwner/晉系]南昌
 [CityOwner/晉系]贛州
 [CityOwner/晉系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 晉系/-300
 [FREEUPGRADE]
 晉系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/晉系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]16
 Name=中德合作I（直魯聯軍）
Condition
 [PlayerFaction/=]直魯聯軍
 [FactionPPMore/直魯聯軍]35
 [CityOwner/直魯聯軍]南昌
 [CityOwner/直魯聯軍]贛州
 [CityOwner/直魯聯軍]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 直魯聯軍/-300
 [FREEUPGRADE]
 直魯聯軍/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/直魯聯軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]17
 Name=稅警總團成立
Condition
 [PlayerFaction/=]國民政府
 [FactionPPMore/國民政府]45
 [CityOwner/國民政府]上海
 [CityOwner/國民政府]南京
 [CityOwner/國民政府]杭州
 [CityOwner/國民政府]溫州
 [CityOwner/國民政府]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 國民政府/-500
 [FREEUPGRADE]
 國民政府/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]18
 Name=稅警總團成立（五省聯軍）
Condition
 [PlayerFaction/=]五省聯軍
 [FactionPPMore/五省聯軍]45
 [CityOwner/五省聯軍]上海
 [CityOwner/五省聯軍]南京
 [CityOwner/五省聯軍]杭州
 [CityOwner/五省聯軍]溫州
 [CityOwner/五省聯軍]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 五省聯軍/-500
 [FREEUPGRADE]
 五省聯軍/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]19
 Name=稅警總團成立（皖系）
Condition
 [PlayerFaction/=]皖系
 [FactionPPMore/皖系]45
 [CityOwner/皖系]上海
 [CityOwner/皖系]南京
 [CityOwner/皖系]杭州
 [CityOwner/皖系]溫州
 [CityOwner/皖系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 皖系/-500
 [FREEUPGRADE]
 皖系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]20
 Name=稅警總團成立（國民軍）
Condition
 [PlayerFaction/=]國民軍
 [FactionPPMore/國民軍]45
 [CityOwner/國民軍]上海
 [CityOwner/國民軍]南京
 [CityOwner/國民軍]杭州
 [CityOwner/國民軍]溫州
 [CityOwner/國民軍]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 國民軍/-500
 [FREEUPGRADE]
 國民軍/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]21
 Name=稅警總團成立（桂系）
Condition
 [PlayerFaction/=]桂系
 [FactionPPMore/桂系]45
 [CityOwner/桂系]上海
 [CityOwner/桂系]南京
 [CityOwner/桂系]杭州
 [CityOwner/桂系]溫州
 [CityOwner/桂系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 桂系/-500
 [FREEUPGRADE]
 桂系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]22
 Name=稅警總團成立（川康軍）
Condition
 [PlayerFaction/=]川康軍
 [FactionPPMore/川康軍]45
 [CityOwner/川康軍]上海
 [CityOwner/川康軍]南京
 [CityOwner/川康軍]杭州
 [CityOwner/川康軍]溫州
 [CityOwner/川康軍]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 川康軍/-500
 [FREEUPGRADE]
 川康軍/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]23
 Name=稅警總團成立（奉系）
Condition
 [PlayerFaction/=]奉系
 [FactionPPMore/奉系]45
 [CityOwner/奉系]上海
 [CityOwner/奉系]南京
 [CityOwner/奉系]杭州
 [CityOwner/奉系]溫州
 [CityOwner/奉系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 奉系/-500
 [FREEUPGRADE]
 奉系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]24
 Name=稅警總團成立（直系）
Condition
 [PlayerFaction/=]直系
 [FactionPPMore/直系]45
 [CityOwner/直系]上海
 [CityOwner/直系]南京
 [CityOwner/直系]杭州
 [CityOwner/直系]溫州
 [CityOwner/直系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 直系/-500
 [FREEUPGRADE]
 直系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]25
 Name=稅警總團成立（川軍）
Condition
 [PlayerFaction/=]川軍
 [FactionPPMore/川軍]45
 [CityOwner/川軍]上海
 [CityOwner/川軍]南京
 [CityOwner/川軍]杭州
 [CityOwner/川軍]溫州
 [CityOwner/川軍]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 川軍/-500
 [FREEUPGRADE]
 川軍/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]26
 Name=稅警總團成立（滇系）
Condition
 [PlayerFaction/=]滇系
 [FactionPPMore/滇系]45
 [CityOwner/滇系]上海
 [CityOwner/滇系]南京
 [CityOwner/滇系]杭州
 [CityOwner/滇系]溫州
 [CityOwner/滇系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 滇系/-500
 [FREEUPGRADE]
 滇系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]27
 Name=稅警總團成立（黔系）
Condition
 [PlayerFaction/=]黔系
 [FactionPPMore/黔系]45
 [CityOwner/黔系]上海
 [CityOwner/黔系]南京
 [CityOwner/黔系]杭州
 [CityOwner/黔系]溫州
 [CityOwner/黔系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 黔系/-500
 [FREEUPGRADE]
 黔系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]28
 Name=稅警總團成立（晉系）
Condition
 [PlayerFaction/=]晉系
 [FactionPPMore/晉系]45
 [CityOwner/晉系]上海
 [CityOwner/晉系]南京
 [CityOwner/晉系]杭州
 [CityOwner/晉系]溫州
 [CityOwner/晉系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 晉系/-500
 [FREEUPGRADE]
 晉系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]29
 Name=稅警總團成立（直魯聯軍）
Condition
 [PlayerFaction/=]直魯聯軍
 [FactionPPMore/直魯聯軍]45
 [CityOwner/直魯聯軍]上海
 [CityOwner/直魯聯軍]南京
 [CityOwner/直魯聯軍]杭州
 [CityOwner/直魯聯軍]溫州
 [CityOwner/直魯聯軍]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 直魯聯軍/-500
 [FREEUPGRADE]
 直魯聯軍/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]30
 Name=刺殺袁祖銘
Condition
 [FactionExist/=]黔系
 [FactionExist/=]國民政府
 [FactionExist/=]湘系
 [FactionDefeat/=]直系
 [CityOwner/黔系]常德
Script
 [PLAYBGM]
 [TEXT]
 北伐過程中，不少軍閥中途加入北伐軍，湘系軍閥唐生智和黔軍總司令袁祖銘亦是其中之一。
 [TX]
 [WAIT]
 [TEXT]
 唐生智驅走長官湖南省長趙恆惕，並自任為湖南省
 長。袁祖銘則因為滇系對貴州的干涉以及貧瘠的貴州難以供養
 大軍，已經在各省轉戰數年，擁眾數萬，這次則欲進據湘西，並在常德攤派賦稅，招募兵勇。
 [TX]
 [WAIT]
 [TEXT]
 唐生智欲圖獨霸湖南，於是決心除掉袁祖銘。某晚，唐生智設
 宴邀請袁祖銘。
 [TX]
 [WAIT]
 [FACE2]
 王天培/王天培
 [SAY2]
 恐怕是鴻門宴，還是不去的好。
 [TX]
 [WAIT]
 [QUESTION]
 是否赴宴？
 [TX]
 [ANSWER]
 歷史/去
 假想/不去
 [ASK]
 黔系/歷史
 [END]
 [LABEL]
 歷史
 [FACE1]
 袁祖銘/袁祖銘
 [SAY1]
 放心好了，他敢動我，我踏平他。
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 袁祖銘對自己的軍事實力頗具自信，於是不顧部下勸阻前往赴
 宴。
 [TX]
 [WAIT]
 [TEXT]
 宴會上
 [TX]
 [WAIT]
 [FACE2]
 袁祖銘/袁祖銘
 [SAY2]
 我軍在湘西只是暫住，將盡快離開湖南。絕無賴在湘西不走的
 企圖，目前只是需要一筆開拔費而已。前些天我們與湖南省政
 府交涉過了，他們回電說我們屬於中央直轄部隊，省府無力為
 我們籌措經費。這對我們下一步北伐非常不利呀！
 [TX]
 [WAIT]
 [FACE1]
 唐生智/唐生智
 [SAY1]
 本人對貴軍駐紮湘西是毫不介意的，我已經指示湖南省政府為
 貴軍再籌撥一個月的糧餉，作為貴軍的開拔費用，請您放心好
 了。
 [TX]
 [WAIT]
 [SAY2]
 多謝唐總指揮的關照，等拿到這筆經費之後我軍留湘部隊一定
 盡快整頓完畢，剋日北上。
 [TX]
 [WAIT]
 [SAY1]
 糟了，這幾天我正鬧肚子，現在肚子裡又折騰起來。對不起了
 ，諸位，我要去趟廁所方便一下。你們先吃著，我去去就來。
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 唐生智下樓沒有回席，隨後上樓的湘軍教導師部隊將袁祖銘擒
 殺。
 [TX]
 [WAIT]
 [TEXT]
 同屬國民革命軍的兩位總指揮竟在北伐途中同互相殘殺。實際上，國民革命軍只是由各路軍閥拼湊而成，其內鬥也只是
 軍閥混戰的延續。
 [TX]
 [WAIT]
 [TEXT]
 而黔軍失去了強人袁祖銘，漸漸走向沒落。
 [TX]
 [WAIT]
 [DISBAND]
 袁祖銘
 [COMMANDER]
 黔系/周西成
 [CITYOWNER]
 常德/湘系
 [PEACEALL]
 黔系
 [END]
 [LABEL]
 假想
 [FACE1]
 袁祖銘/袁祖銘
 [SAY1]
 說得也對，雖然我軍不用把唐生智這小子放在眼裡。但還是該提防他暗算我們。
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 唐生智眼見袁祖銘並不上當，對黔軍久據湘西感到壓力的唐生智為了根除後方的威脅，終於悍然向黔軍宣戰。
 [TX]
 [WAIT]
 [TEXT]
 同屬國民革命軍的兩軍竟在北伐途中同互相殘殺。但實際上，國民革命軍其實是由各路軍閥拼湊而成，其內鬥也只是軍閥混戰的延續。
 [TX]
 [WAIT]
 [WAR]
 湘系/黔系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]31
 Name=二六政變
Condition
 [Turn/=]24
 [FactionExist/=]滇系
 ![FactionCityMore/滇系]4
Script
 [PLAYBGM]
 [TEXT]
 民國初年，唐繼堯經蔡鍔的推薦擔任雲南都督。
 [TX]
 [WAIT]
 [TEXT]
 唐繼堯統治雲南後，開始大肆擴軍，並積極向各省擴張。並響
 應孫中山的南方政府，其號令在極盛時曾經遍及八省。
 [TX]
 [WAIT]
 [TEXT]
 但隨著部將的兵變分裂，以及對外軍事行動的接連失敗，唐繼
 堯依舊窮兵黷武，但威望已經大不如前。
 [TX]
 [WAIT]
 [PICTURE]
 佽飛軍/佽飛軍
 [TEXT]
 一日，曾任唐繼堯衛隊「佽飛軍」隊長的龍雲等人發動兵變，迫使唐繼堯
 倒台，結束了其在雲南１６年的統治。數月後，唐繼堯死於昆明，年４４歲。
 [TX]
 [WAIT]
 [PICTURE]
 唐繼堯/唐繼堯
 [TEXT]
 在討袁戰爭和護法戰爭都擔任要角，被譽為護國和靖國元勳的
 唐繼堯，在亂世的政局中失勢，就這樣不明不白的死去，黯然從歷
 史舞台中退場．．．．．．
 [TX]
 [WAIT]
 [DISBAND]
 唐繼堯
 [GAINUNIT]
 滇系/龍雲
 [COMMANDER]
 滇系/龍雲
 [PEACEALL]
 滇系
 [LEADERALIAS]
 龍雲/雲南王
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]32
 Name=三七政變
Condition
 [Turn/=]30
 [FactionExist/=]新疆
 ![FactionCityMore/新疆]4
Script
 [PLAYBGM]
 [PICTURE]
 楊增新/楊增新
 [TEXT]
 民國建立以來，楊增新的統治使新疆在民族、經濟、外交問題上都
 獲得和緩的發展，其巧妙平衡內外各勢力的經營使得新疆成為戰亂中的一片樂土。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [TEXT]
 但是民國１７年，楊增新卻在俄文法政專門學校的畢業生慶賀
 宴上，忽遭時軍務廳長，外交署長樊耀南一派所暗殺。
 [TX]
 [WAIT]
 [PICTURE]
 金樹仁/金樹仁
 [TEXT]
 樊耀南迅速被政務廳長金樹仁逮捕處死，然而有人懷疑此事為金樹仁與
 當時欲窺西北的馮玉祥所合謀，身為文職的樊耀南只是被栽贓。但事情的
 真相不得而知．．．
 [TX]
 [WAIT]
 [PICTURE]
 *
 [TEXT]
 政績卓著的楊增新死後，新疆也不能再保住在亂世中的平和，漸漸陷入了
 不安與動亂中．．．
 [TX]
 [WAIT]
 [DISBAND]
 楊增新
 [GAINUNIT]
 新疆/金樹仁
 [COMMANDER]
 新疆/金樹仁
 [WAR]
 馬家軍/新疆
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]33
 Name=中德合作I（湘系）
Condition
 [PlayerFaction/=]湘系
 [FactionPPMore/湘系]35
 [CityOwner/湘系]南昌
 [CityOwner/湘系]贛州
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 湘系/-300
 [FREEUPGRADE]
 湘系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/湘系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]34
 Name=稅警總團成立（湘系）
Condition
 [PlayerFaction/=]湘系
 [FactionPPMore/湘系]45
 [CityOwner/湘系]上海
 [CityOwner/湘系]南京
 [CityOwner/湘系]杭州
 [CityOwner/湘系]溫州
 [CityOwner/湘系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 湘系/-500
 [FREEUPGRADE]
 湘系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]35
 Name=誓師北伐
Condition
 [Turn/>]14
 [FactionExist/=]湘系
 [FactionExist/=]國民政府
 [AtWar/直系]國民軍
Script
 [TEXT]
 民國９年，趙恆惕驅逐了譚延闓與程潛的勢力，自任為湖南省
 長，創制省憲並提倡聯省自治。
 [TX]
 [WAIT]
 [TEXT]
 湖南在趙的治下享有了清末以來少見的數年和平，但與此同時
 ，省防軍四師中的唐生智勢力擴大，逐漸不受趙的節制。
 [TX]
 [WAIT]
 [TEXT]
 趙恆惕曾收容在二次直奉戰爭中下野的吳佩孚，於吳有恩。因
 此，趙恆惕以吳佩孚為後盾，試圖收回唐生智的職權。
 [TX]
 [WAIT]
 [TEXT]
 唐生智無意就範，率部將趙恆惕驅出湖南。此舉引來吳佩孚派
 兵南下，唐生智自知不敵，於是發電向廣西的李宗仁求援。
 [TX]
 [WAIT]
 [TEXT]
 李宗仁派出主力第七軍前往湖南助戰，並且親赴廣州邀請國民
 政府共同北伐。
 [TX]
 [WAIT]
 [PLAYBGM]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 此時北方軍閥混戰，我們正可用唐生智作為北伐的前鋒，打開
 通往湖南的道路。如果不把握這千載難逢的良機，問鼎中原的
 機會可能一逝永不再來。
 [TX]
 [WAIT]
 [FACE2]
 譚延闓/譚延闓
 [SAY2]
 你要唐生智加入革命？他恐怕靠不住吧！
 [TX]
 [WAIT]
 [FACE2]
 程潛/程潛
 [SAY2]
 唐生智那小子以前幫北洋軍閥打我們：現在吳佩孚打他，你要我們去救他？不如先讓吳佩孚把唐打垮了，我們再去收編唐的部隊，到時候再談北伐也不遲。
 [TX]
 [WAIT]
 [FACE2]
 鮑羅廷/鮑羅廷
 [SAY2]
 北伐茲事體大，應該從長考慮．．．。
 [TX]
 [WAIT]
 [QUESTION]
 是否發動北伐？
 [TX]
 [ANSWER]
 歷史/實行總理遺志！
 假想/時機尚未成熟
 [ASK]
 國民政府/歷史
 [END]
 [LABEL]
 歷史
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 ．．．．．．現在正是實現總理遺志的時候！
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 雖然包括共產國際代表在內的廣州多數軍政領袖都不贊成北伐
 ，但在軍委會主席蔣中正的力排眾議下，北伐得以成行。
 [TX]
 [WAIT]
 [PICTURE]
 北伐誓師/北伐誓師
 [TEXT]
 於是，蔣中正就任國民革命軍總司令，誓師北伐。唐生智所部
 則改編為國民革命軍第八軍，同時黔軍也響應北伐，進軍湘西
 。
 [TX]
 [WAIT]
 [PICTURE]
 誓師北伐/誓師北伐
 [TEXT]
 孫中山曾經試圖進行北伐統一中國，然齎志以歿。現在其繼承
 者能完成其遺志嗎？
 [TX]
 [WAIT]
 [FREEUPGRADE]
 國民政府/蘇式步兵
 [WAR]
 國民政府/直系
 [WAR]
 湘系/直系
 [WAR]
 桂系/直系
 [COMMANDER]
 湘系/唐生智
 [DISBAND]
 趙恆惕
 [DISBAND]
 葉開鑫
 [DISBAND]
 賀耀祖
 [DISBAND]
 劉鉶
 [CITYOWNER]
 常德/黔系
 [ALLIANCE]
 國民政府/湘系
 [ALLIANCE]
 國民政府/黔系
 [GAINUNIT]
 湘系/顧淨緣
 [UNITCLASS]
 顧淨緣/內閣
 [END]
 [LABEL]
 假想
 [FACE2]
 蔣中正/蔣中正
 [SAY2]
 廣州的情形還太複雜．．．．．．現在如何能談到北伐呢？
 [TX]
 [WAIT]
 [FACE1]
 李宗仁/李宗仁
 [SAY1]
 ．．．．．．。
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 由於包括共產國際代表和軍校校長蔣中正在內的廣州多數軍政領袖都不贊成北伐，入湘支援唐生智的計畫被迫放棄。
 [TX]
 [WAIT]
 [TEXT]
 護法戰爭中，孫中山曾經試圖進行北伐統一中國，然齎志以歿。現在其繼承者為了不重蹈覆轍，決心不貿然投入他省的戰事，而先於廣東休養生息，徐圖後進。
 [TX]
 [WAIT]
 [WAR]
 直系/湘系
 [GAINUNIT]
 湘系/唐生智
 [COMMANDER]
 湘系/唐生智
 [DISBAND]
 趙恆惕
 [DISBAND]
 葉開鑫
 [DISBAND]
 賀耀祖
 [DISBAND]
 劉鉶
 [GAINUNIT]
 湘系/顧淨緣
 [UNITCLASS]
 顧淨緣/內閣
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]36
 Name=蔣宋聯姻
Condition
 [FactionExist/=]國民政府
 [FactionPPMore/國民政府]30
 [CityOwner/國民政府]上海
 [Event/=]下野宣言
Script
 [PLAYBGM]
 [TEXT]
 北伐途中，蔣中正排除了內部共產黨，國民黨的聯俄容共政策
 宣告破裂。
 [TX]
 [WAIT]
 [TEXT]
 然而，主使清黨的蔣中正本人卻也成為黨內眾矢之的。
 [TX]
 [WAIT]
 [TEXT]
 為此，在與蘇聯的合作破裂後，蔣中正急需尋求其他的外援支持。
 [TX]
 [WAIT]
 [TEXT]
 以宋子文孔祥熙為首的財團，提出了讓蔣中正迎娶宋子文之妹宋美齡的策略聯姻，以換取他們對蔣在財政上的支持。
 [TX]
 [WAIT]
 [TEXT]
 迎娶孫中山的小姨子對蔣的政治號召力亦極有益，能讓他以孫中山的繼承者自居。另一方面，孔宋財團亦能為蔣打開對美國交涉的大門。
 [TX]
 [WAIT]
 [PICTURE]
 蔣中正與陳潔如/蔣中正與陳潔如
 [TEXT]
 為了迎娶宋美齡，蔣中正必須與此時身為校長夫人的陳潔如離
 異，並將其送往美國五年。實際上，宋美齡為蔣的第四位配偶。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [PICTURE]
 蔣宋聯姻/蔣宋聯姻
 [TEXT]
 蔣中正與宋美齡的婚姻在上海大華飯店舉行，一方為中國的軍
 事強人，一方為政經兩界呼風喚雨的孔宋財團。這場婚禮立刻
 獲得全國的矚目，婚禮的影片甚至成為上海戲院的加映片。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [PICTURE]
 蔣宋聯姻二/蔣宋聯姻二
 [TEXT]
 中國現代最輝煌奪目的一場婚禮舉行了，其將為中國帶來什麼
 影響呢．．．？
 [TX]
 [WAIT]
 [PICTURE]
 *
 [GAINMONEY]
 國民政府/500
 [REFORM]
 國民政府/FreeMarket
 [LEADERFACTION]
 宋美齡/黃埔系
 [LEADERTYPE]
 宋美齡/親屬人物
 [LEADERVALUE]
 宋美齡/蔣中正
 [END]
 
[/SCRIPTEVENT]
[SCRIPTEVENT]37
 Name=中原大戰
Condition
 [Event/=]皇姑屯事件
 [FactionExist/=]國民政府
 [FactionExist/=]晉系
 [FactionExist/=]國民軍
 [FactionExist/=]桂系
 [FactionCityMore/國民政府]15
Script
 [PLAYBGM]
 [PICTURE]
 E037a/北伐完成
 [TEXT]
 北伐完成後，全國統一以蔣中正為首的國民政府為新的中央政
 府。
 [TX]
 [WAIT]
 [TEXT]
 但此時的中國徒具形式上的統一，中央政府的實際控制區只有
 東南一隅，地方對中央呈現獨立或半獨立的狀態。甚至還必須支付預算給不受號令，獨立自主的各地軍隊。
 [TX]
 [WAIT]
 [PICTURE]
 中原大戰/中原大戰
 [TEXT]
 為此，國民政府主席蔣中正決心推動全國軍隊的中央化，編遣
 其他派系的軍隊。
 [TX]
 [WAIT]
 [TEXT]
 但此時全國各地有擁強大勢力的軍事派系擔心遭到蔣中正的中央政府各個擊破與架空併吞，終於大舉聯合反蔣。
 [TX]
 [WAIT]
 [PICTURE]
 閻錫山/閻錫山
 [TEXT]
 閻錫山
 [TX]
 [WAIT]
 [PICTURE]
 馮玉祥/馮玉祥
 [TEXT]
 馮玉祥
 [TX]
 [WAIT]
 [PICTURE]
 李宗仁二/李宗仁二
 [TEXT]
 李宗仁
 [TX]
 [WAIT]
 [PICTURE]
 E037b/中原大戰2
 [TEXT]
 共同另立國民政府中央，並推閻錫山為中華民國陸海空軍總司
 令，馮、李為副司令，三方各自在其根據地宣誓就職，決心與
 蔣中正的中央軍一決死戰。
 [TX]
 [WAIT]
 [TEXT]
 民國建立以來最大規模的內戰爆發了，華夏神州究竟鹿死誰手
 ？中國將走向何種命運呢？
 [TX]
 [WAIT]
 [WAR]
 國民軍/國民政府
 [WAR]
 晉系/國民政府
 [WAR]
 桂系/國民政府
 [ALLIANCE]
 國民軍/晉系
 [CITYOWNER]
 開封/國民軍
 [CITYOWNER]
 鄭州/國民軍
 [CITYOWNER]
 洛陽/國民軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]38
 Name=西去的騎手
Condition
 [FactionExist/=]新疆
 [CityOwner/馬家軍]哈密
 [Event/=]三七政變
Script
 [PLAYBGM]
 [TEXT]
 金樹仁主政新疆以來，增加稅賦和對穆斯林實行高壓政策，又
 廢止了哈密自清朝以來的土司政策，終於引起了穆斯林的大規
 模反抗。
 [TX]
 [WAIT]
 [PICTURE]
 馬仲英騎馬/馬仲英騎馬
 [TEXT]
 此時西北的馬仲英受到同族馬步芳的壓迫，正求向外發展，於
 是受穆斯林反抗軍之邀，率部唱著「馬步芳、操你娘，攆著老子上新疆，白蠟杆子換鋼槍。」的軍歌西進新疆。
 [TX]
 [WAIT]
 [TEXT]
 馬仲英入疆時只有４００人，但迅速吸引群眾加入而擴大，其軍隊成
 分相當複雜，從日本人到土耳其人均有。
 [TX]
 [WAIT]
 [TEXT]
 新疆省軍不斷被馬仲英以寡擊眾擊破，西北震動。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [PICTURE]
 盛世才/盛世才
 [TEXT]
 此時，金樹仁的部將盛世才藉著時局動亂叛變，迫使金樹仁下
 野。
 [TX]
 [WAIT]
 [TEXT]
 為求自保，盛世才與蘇聯簽訂了秘密協定，得到大量的蘇聯軍
 火援助。但仍舊為馬仲英大破圍困，情況危急。
 [TX]
 [WAIT]
 [PICTURE]
 馬家軍/馬家軍
 [TEXT]
 此時，蘇聯終於出兵援救盛世才，干涉新疆。馬仲英率領
 著拼湊的落後部隊與有全面現代陸空火力優勢的蘇軍纏鬥了兩
 個月，終於被其擊破。
 [TX]
 [WAIT]
 [TEXT]
 在蘇聯的干涉下，馬仲英只能和盛世才達成停戰協定。其後，
 馬仲英在其部下的共產黨員鼓動下，前往蘇聯遊歷學習。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [FACE1]
 馬仲英/馬仲英
 [SAY1]
 總有一天我要征服全中國，然後再花三年時間征服蘇聯，最後
 ，把我們的邊界推到土耳其，建立一個大伊斯蘭國家．．．．
 ．．。
 [TX]
 [WAIT]
 [FACE1]
 *
 [TEXT]
 馬仲英西去後失去音訊，自此生死不明。而新疆在此次事件後
 不能再維持楊增新時代的主權，成為了蘇聯的利益範圍．
 ．．。
 [TX]
 [WAIT]
 [DISBAND]
 金樹仁
 [KILLLEADER]
 馬仲英
 [GAINUNIT]
 新疆/盛世才
 [COMMANDER]
 新疆/盛世才
 [UNITCLASS]
 盛世才/蘇式步兵
 [LEADERALIAS]
 盛世才/新疆王
 [CITYOWNER]
 哈密/新疆
 [PEACEALL]
 新疆
 [REFORM]
 新疆/Socialism
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]39
 Name=中德合作I（粵系）
Condition
 [PlayerFaction/=]粵系
 [FactionPPMore/粵系]35
 [CityOwner/粵系]南昌
 [CityOwner/粵系]贛州
 [CityOwner/粵系]瑞金
Script
 [PLAYBGM]
 [TEXT]
 在一次世界大戰中失敗的德國失去了在中國的租界，但是這也
 為中德關係的改善減少了障礙。民國１０年，雙方簽訂了中國近
 代史上少見的平等條約《中德協約》。
 [TX]
 [WAIT]
 [TEXT]
 隨著中國武器及軍用物資市場的擴大，和在內戰中具現代化外貌的較有力
 中央政府出現。首任德國軍事顧問，馬克斯·鮑爾受邀來華。
 [TX]
 [WAIT]
 [FACE2]
 馬克斯．鮑爾/馬克斯．鮑爾
 [SAY2]
 必須將軍政大權集中於中央政府，以大刀闊斧手段剷除一切離心力量，進行一切加強中央權威的必要改革。
 [TX]
 [WAIT]
 [FACE2]
 *
 [TEXT]
 中德在軍事和經濟上的初步合作開始。
 [TX]
 [WAIT]
 [GAINMONEY]
 粵系/-300
 [FREEUPGRADE]
 粵系/德式步兵
 [LEADERTYPE]
 法肯豪森/勢力人物
 [LEADERVALUE]
 法肯豪森/粵系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]40
 Name=稅警總團成立（粵系）
Condition
 [PlayerFaction/=]粵系
 [FactionPPMore/粵系]45
 [CityOwner/粵系]上海
 [CityOwner/粵系]南京
 [CityOwner/粵系]杭州
 [CityOwner/粵系]溫州
 [CityOwner/粵系]寧波
Script
 [PLAYBGM]
 [TEXT]
 民國成立時雖建立了一套鹽務緝私制度，但運作上並不成功，
 政府的鹽稅收入大量流失。
 [TX]
 [WAIT]
 [TEXT]
 宋子文出任財政部長後，在鹽務制度上進行了改革，在全國設立了鹽務稽核所，並將鹽務機關權力集中。
 [TX]
 [WAIT]
 [FACE2]
 宋子文/宋子文
 [SAY2]
 僅在制度上改革是不夠的，必須建立一支精良的緝私部隊才能夠保障鹽務改革的深入進行，否則不足以打擊抗稅。
 [TX]
 [WAIT]
 [FACE2]
 * 
 [TEXT]
 宋子文對官兵的素質要求甚高，裝備亦由財政部自行採購美國軍備，精良程度非一般部隊可比。
 [TX]
 [WAIT]
 [TEXT]
 於是，在宋子文的苦心經營下，一支採美式裝備的精銳部隊誕生了。
 [TX]
 [WAIT]
 [GAINMONEY]
 粵系/-500
 [FREEUPGRADE]
 粵系/美式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]41
 Name=覺醒的巨人
Condition
 [CityNotOwner/美國]馬尼拉
Script
 [GAINOFFBOARDSP]
 美國/100
 [GAINOFFBOARDTP]
 美國/2850
 [GAINOFFBOARDIP]
 美國/100
 [BANWEAPON]
 美國/0
 [GAINUNIT]
 美國/尼米茲
 [GAINUNIT]
 美國/金恩
 [GAINUNIT]
 美國/海爾賽
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]42
 Name=日泰同盟
Condition
 [AtWar/大日本帝國]泰國
Script
 [ALLIANCE]
 大日本帝國/泰國
 [NEUTRALITY]
 泰國/100
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]43
 Name=共產國際對中共的援助
Condition
 [Event/=]清黨
 [CityNotOwner/共產黨]瑞金
Script
 [GAINOFFBOARDTP]
 共產黨/25
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]93
 Name=共產國際對國民政府的援助
Condition
 ![PlayerFaction/=]國民政府
 ![PlayerFaction/=]粵系
 [FactionExist/=]國民政府
Script
 [GAINMONEY]
 國民政府/1000
 [GAINOFFBOARDSP]
 國民政府/60
 [FREEUPGRADE]
 國民政府/蘇式步兵
 [ALLLEVELUP]
 國民政府/3
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]94
 Name=五卅慘案
Condition
 [Turn/=]4
 [FactionExist/=]國民政府
Script
 [PLAYBGM]
 [PICTURE]
 五卅慘案1/五卅慘案1
 [TEXT]
 民國１４年二月，上海日商工廠發現一具疑似遭管理人員毆打致死的童工屍體。平日屢遭外商欺凌的上海工人憤而聯合進行罷工，向雇主爭取改善待遇。
 [TX]
 [WAIT]
 [TEXT]
 活動得到青島的工人和知識份子響應，各大學學生到租界各處演講宣傳民族主義，反對外國在華勢力。五月３０日，青島抗議群眾遭到武力鎮壓，死傷數十人。
 [TX]
 [WAIT]
 [PICTURE]
 五卅慘案2/五卅慘案2
 [TEXT]
 此事件激起了中國社會對外國勢力的不滿，全國各地陸續出現反抗外國在華勢力的風潮，在以國民政府為首的國共兩黨帶領下，全國各大城市發起了學生罷課、工人罷工、商人罷市運動。
 [TX]
 [WAIT]
 [TEXT]
 但在列強壓力下，各地群眾運動遭到北洋軍閥的取締與鎮壓。然而，這只是中國新一波收回租界、主權與反帝國主義運動火苗的開始。
 [TX]
 [WAIT]
 [SPPERCENT]
 上海/50
 [SPPERCENT]
 香港/50
 [SPPERCENT]
 青島/50
 [ALLPOLICE]
 五省聯軍/-50
 [ALLPOLICE]
 直魯聯軍/-50
 [ALLPOLICE]
 直系/-50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]95
 Name=直奉聯盟
Condition
 ![Event/=]皇姑屯事件
 [CityOwner/國民軍]北京
 [FactionExist/=]直系
 [Event/=]反奉戰爭
Script
 [PLAYBGM]
 [PICTURE]
 直奉聯盟1/直奉聯盟1
 [TEXT]
 馮玉祥距二次直奉戰爭後與張作霖稱兄道弟僅不到一年的光景雙方的矛盾就已表面化而關係破裂。馮玉祥一手策動反奉戰爭，收買張作霖大將郭松齡倒戈，奉系幾乎傾覆。
 [TX]
 [WAIT]
 [TEXT]
 當馮張惡戰之際，在二次直奉戰爭中失勢的吳佩孚原本大可對奉軍落井下石或坐山觀虎鬥，但吳佩孚竟悍然決定與張作霖聯手出兵討馮，此舉對於落難的張作霖來說可謂雪中送炭。
 [TX]
 [WAIT]
 [PICTURE]
 馮玉祥/馮玉祥
 [TEXT]
 馮玉祥知道吳佩孚可能是為了報倒戈之仇而來，於是斷然選擇下野遠赴蘇聯以求能和吳佩孚談和，國民軍頓時群龍無首。
 [TX]
 [WAIT]
 [TEXT]
 國民軍諸將為求免於遭到直奉南北夾擊，決定再次投靠故主吳佩孚。並為求向吳佩孚輸誠，極盡阿諛奉承之能事。
 [TX]
 [WAIT]
 [PICTURE]
 *
 [FACE1]
 張其鍠/張其鍠
 [SAY1]
 司令，國民軍發表聲明決定願意全體投誠我方，並表示絕對服從命令！
 [TX]
 [WAIT]
 [FACE2]
 吳佩孚/吳佩孚
 [SAY2]
 ‧‧‧‧‧‧
 [TX]
 [WAIT]
 [SAY1]
 我們該如何答覆他們？
 [TX]
 [WAIT]
 [SAY2]
 ‧‧‧‧‧‧叫他們全體繳械，否則不接受投降。
 [TX]
 [WAIT]
 [SAY1]
 但他們不可能接受繳械這種條件的，困獸猶鬥，這是逼馮軍與我們為敵啊！
 [TX]
 [WAIT]
 [SAY2]
 人無信不立，我既先與奉軍有盟攻馮在先，若再接受馮軍歸降，背約助其攻奉，豈不成了背信棄義的卑鄙小人？
 [TX]
 [WAIT]
 [SAY1]
 司令！不論馮軍真心歸順與否，我們都可命其與奉軍交戰，待其兩敗俱傷，再將其一舉殲之。這是勝利旋師北京，重組中央政府的良機啊！
 [TX]
 [WAIT]
 [SAY2]
 ‧‧‧‧‧‧
 [TX]
 [QUESTION]
 是否收編國民軍？
 [TX]
 [ANSWER]
 歷史/不和叛徒妥協，更不能背信棄義！
 假想/即使媾和背約，也不能放過此大好機會‧‧‧
 [ASK]
 直系/歷史
 [END]
 [LABEL]
 歷史
 [FACE2]
 吳佩孚/吳佩孚
 [PLAYBGM]
 [SAY2]
 馮軍裡通蘇俄，禍亂中國，赤禍不可不防，政綱不可不振！這已不是區區恩怨問題，而是是非問題！
 [TX]
 [WAIT]
 [FACE1]
 張其鍠/張其鍠
 [SAY1]
 此事不可不慎，還望司令再多考慮‧‧‧。
 [TX]
 [WAIT]
 [FACE2]
 吳佩孚/吳佩孚
 [SAY2]
 住口！
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [PICTURE]
 直奉聯盟2/直奉聯盟2
 [TEXT]
 吳佩孚堅守盟約拒絕國民軍歸附，並與張作霖會晤商議聯攻國民軍。其對信義價值的堅持、不肯欺世取巧的原則與不願在政治上隨機應變，使其選擇了艱難的道路。
 [TX]
 [WAIT]
 [TEXT]
 而山西閻錫山見直奉聯盟之勢不可當，亦率軍加入對國民軍的圍攻，失去馮玉祥的國民軍陷入三面包圍，情勢甚危‧‧‧。
 [TX]
 [WAIT]
 [WAR]
 晉系/國民軍
 [WAR]
 直系/國民軍
 [DISBAND]
 馮玉祥
 [COMMANDER]
 國民軍/鹿鐘麟
 [UNITCLASS]
 鹿鐘麟/蘇式步兵
 [DISBAND]
 蔣百里
 [END]
 [LABEL]
 假想
 [FACE2]
 吳佩孚/吳佩孚
 [PLAYBGM]
 [SAY2]
 ‧‧‧‧‧‧張省長言之有理，我們就權且先接受馮部的投誠。
 [TX]
 [WAIT]
 [FACE1]
 *
 [FACE2]
 *
 [TEXT]
 經過二次直奉戰爭失敗打擊的歷練，吳佩孚終於改變以往剛直不取巧的原則，選擇和現實的政治利益妥協。而其不能貫徹信義到最後的轉變令人不得不感概。
 [TX]
 [WAIT]
 [TEXT]
 而在直奉聯盟破裂，轉為直馮聯盟反奉的情況下，北方的局勢將會產生什麼變化呢‧‧‧？
 [TX]
 [WAIT]
 [WAR]
 直系/奉系
 [MASTER]
 直系/國民軍
 [DISBAND]
 馮玉祥
 [COMMANDER]
 國民軍/鹿鐘麟
 [UNITCLASS]
 鹿鐘麟/蘇式步兵
 [CITYOWNER]
 北京/直系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]96
 Name=三一八慘案
Condition
 [Turn/=]14
 [CityOwner/皖系]北京
Script
 [PICTURE]
 三一八慘案1/三一八慘案1
 [PLAYBGM]
 [TEXT]
 民國１５年３月１２日，與國民軍交戰中的奉軍在日本軍艦的護送下進入大沽口，遭國民軍砲擊逐出。事後日本認為國民軍破壞了《辛丑條約》，與英、美、法、意、荷、比、西等７國公使向北洋政府提出拆除大沽口防禦工事的最後通牒。
 [TX]
 [WAIT]
 [PICTURE]
 三一八慘案2/三一八慘案2
 [TEXT]
 此舉激起了北京各界人士的抗議，３月１８日，在國共兩黨的率領下，發起了以學生為主之約５０００人要求反對八國通牒，驅逐八國公使，廢除一切不平等條約，撤退外國軍艦的抗議遊行。
 [TX]
 [WAIT]
 [PLAYBGM]
 [TEXT]
 然而在抗議群眾行經執政府，要求面見中華民國臨時執政段祺瑞以陳情時，竟遭到軍警的武力強行鎮壓。抗議群眾死傷２００餘人，而後軍警在清理現場時，竟然將死者財物盡行掠去，甚至連衣服也全部剝光。
 [TX]
 [WAIT]
 [PICTURE]
 三一八慘案3/三一八慘案3
 [TEXT]
 究竟誰下令軍警動武不得而知，事發後全國各地輿論紛紛譴責國務院門口對學生的屠殺，魯迅稱三一八為：「民國以來最黑暗的一天」。
 [TX]
 [WAIT]
 [TEXT]
 此事使得段祺瑞之執政府威信大受打擊，國民軍決定趁此以通奉之罪名武力驅逐段祺瑞，迫使其執政府倒台。而事後奉軍張學良則在北京大肆迫害、搜捕抗議人士與報業人員，北京政府的形勢再度陷入混亂‧‧‧‧‧‧。
 [TX]
 [WAIT]
 [WAR]
 國民軍/皖系
 [ALLPOLICE]
 皖系/-50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]97
 Name=中山艦事件
Condition
 [Turn/=]14
 [MasterOf/共產黨]國民政府
Script
 [PLAYBGM]
 [TEXT]
 孫文去世後，留下的是暗潮洶湧的廣州政局。
 [TX]
 [WAIT]
 [PICTURE]
 永豐艦/永豐艦
 [TEXT]
 在廖仲愷被刺、胡漢民、許崇智被流放後，汪精衛成為國民政府的最高領袖，並延續孫文聯俄容共的政策。
 [TX]
 [WAIT]
 [TEXT]
 然而此時，中共跨黨分子掌握了國民政府的多數部門與權力中樞。孫文死後，兩黨的矛盾與摩擦逐漸浮現。
 [TX]
 [WAIT]
 [TEXT]
 民國１５年３月２０日，原名永豐艦的中山艦在調回廣州途中出現了異動。在山雨欲來的氣氛下，身為黃埔軍校校長的蔣中正懷疑是中共意圖利用中山艦進行叛亂奪權，於是下令廣州全城戒嚴。
 [TX]
 [WAIT]
 [PICTURE]
 中山艦/中山艦
 [TEXT]
 蔣中正派兵包圍了中共機關和汪精衛的住所，提出整理黨務案，要求限制中共跨黨分子在國民政府內的權力。汪精衛臨此大變，選擇自行遠赴法國，暫時離開國民黨的權力核心。
 [TX]
 [WAIT]
 [TEXT]
 蔣中正的作為得到了國民黨右派的支持，進一步加強了其在國民政府的聲望，國民黨的聯俄容共政策出現了變化。而中共遭此打擊，對國民政府高層的掌握力減弱，開始轉向下層的群眾運動工作‧‧‧‧‧‧。
 [TX]
 [WAIT]
 [DISBAND]
 汪精衛
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]98
 Name=五原誓師
Condition
 ![CityOwner/直系]長沙
 ![CityOwner/直系]武漢
 ![CityOwner/五省聯軍]贛州
 [FactionExist/=]國民軍
 [Event/=]誓師北伐
 [Event/=]直奉聯盟
Script
 [PLAYBGM]
 [TEXT]
 反奉戰爭後，馮玉祥國民軍遭到了直、晉、奉三軍的圍攻，馮玉祥為先避其鋒，下野遠走蘇聯莫斯科。
 [TX]
 [WAIT]
 [PICTURE]
 馮玉祥/馮玉祥
 [TEXT]
 隨著北伐軍的一路推進，馮玉祥感受到國內形勢的變化，決定回國響應北伐軍與其結成同盟共抗奉軍。
 [TX]
 [WAIT]
 [PICTURE]
 五原誓師/五原誓師
 [TEXT]
 馮玉祥率國民軍在綏遠五原誓師，宣佈所部加入國民黨。馮玉祥在西北接受蘇俄的奧援，而南方的國民政府也有著蘇俄的支持，如今南北呼應，可謂共產國際在中國輸出革命戰略的實現。
 [TX]
 [WAIT]
 [PICTURE]
 五原誓師2/五原誓師2
 [TEXT]
 孫文後半生致力於北伐，但始終未竟全功，如今其後繼者得到了北方馮玉祥的呼應，北伐軍戰局逐漸明朗化‧‧‧‧‧‧。
 [TX]
 [WAIT]
 [GAINUNIT]
 國民軍/馮玉祥
 [COMMANDER]
 國民軍/馮玉祥
 [UNITCLASS]
 馮玉祥/蘇式步兵
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]99
 Name=寧漢分裂
Condition
 [Event/=]清黨
 [FactionExist/=]湘系
 [FactionExist/=]共產黨
 [FactionExist/=]國民政府
 ![CityOwner/五省聯軍]南京
 ![CityOwner/直魯聯軍]南京
 ![CityOwner/奉系]南京
Script
 [PLAYBGM]
 [PICTURE]
 寧漢分裂1/寧漢分裂1
 [TEXT]
 清黨後，以蔣中正為主的北伐軍南京方認為自廣州北遷武漢的國民政府中央已被中共和共產國際控制。胡漢民、蔣中正決定在南京另組國民政府。
 [TX]
 [WAIT]
 [TEXT]
 武漢方面以汪精衛為首、以唐生智、張發奎、程潛等人作為主要軍事力量，並開除蔣中正的國民黨籍並予以通緝，然而相對繼續聯俄容共政策的武漢國民政府來說，蔣中正南京政府的清黨政策得到較多地方軍人的支持。
 [TX]
 [WAIT]
 [PICTURE]
 寧漢分裂2/寧漢分裂2
 [TEXT]
 在李宗仁、朱培德的居中協調下，寧漢雙方暫時免於馬上開戰。但此時，武漢國府內部也逐漸出現不滿中共的聲浪。
 [TX]
 [WAIT]
 [TEXT]
 北伐途中北伐軍陣營發生了分裂，寧漢雙方開始在政治，軍事等多方面展開較量以爭奪正統地位。
 [TX]
 [WAIT]
 [PEACE]
 湘系/國民政府
 [GAINUNIT]
 湘系/汪精衛
 [UNITCLASS]
 汪精衛/內閣
 [CITYOWNER]
 武漢/湘系
 [CITYOWNER]
 南京/國民政府
 [GAINUNIT]
 湘系/張發奎
 [UNITCLASS]
 張發奎/蘇式步兵
 [LEVELUP]
 張發奎/3
 [GAINUNIT]
 湘系/程潛
 [UNITCLASS]
 程潛/砲兵
 [LEVELUP]
 程潛/3
 [GAINUNIT]
 湘系/黃琪翔
 [UNITCLASS]
 黃琪翔/砲兵
 [GAINUNIT]
 湘系/薛岳
 [HEADQUARTER]
 南京/國民政府
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]100
 Name=南昌暴動
Condition
 [FactionExist/=]共產黨
 [FactionExist/=]國民政府
 [Event/=]寧漢分裂
 ![CityOwner/五省聯軍]南昌
 ![CityOwner/直系]洛陽
 ![CityOwner/直系]鄭州
 ![CityOwner/奉系]洛陽
 ![CityOwner/奉系]鄭州
 ![CityOwner/直魯聯軍]洛陽
 ![CityOwner/直魯聯軍]鄭州
Script
 [PLAYBGM]
 [PICTURE]
 E100a/汪精衛
 [TEXT]
 北伐中，國民政府因為「容共」與「清黨」兩路線的衝突，分裂為武漢政府和南京政府。
 [TX]
 [WAIT]
 [TEXT]
 以汪精衛為首的武漢政府雖有心維持國共合作，然而在中共的工農運動越演越烈之下，武漢政府與中共的矛盾表面化，主要將領陸續公開反共。在此情勢下史達林指示共產國際不但不能停止工農運動，更要求汪精衛懲辦反共軍官，汪精衛迫於無奈，終於宣佈武漢政府全面分共。
 [TX]
 [WAIT]
 [PICTURE]
 E100c/鄭州會議
 [TEXT]
 相對於南京政府的武力分共，汪精衛採取和平的分共手段，雖將共產國際顧問鮑羅廷驅逐回國，但並未對共產黨人大肆逮捕或血腥鎮壓。
 [TX]
 [WAIT]
 [TEXT]
 史達林在中國的革命政策遭到挫敗，為此，中共創黨黨魁陳獨秀作為其代罪羔羊，黯然下台‧‧‧
 [TX]
 [WAIT]
 [PICTURE]
 E100b/南昌暴動
 [TEXT]
 然而汪精衛和平分共的期望仍成為泡影，在共產國際的指示下，中共以武裝暴動回應武漢政府的分共。此時中共仍未敢打出自己的旗幟，而是假以國民黨左派之名義指揮軍隊攻占南昌成立政府。
 [TX]
 [WAIT]
 [TEXT]
 自孫文晚年開始的國民黨聯俄容共政策至此結束，不論國民政府中的左派或右派都已與共產黨決裂。中共開始建立起自己的武力，走向武裝奪權之路‧‧‧
 [TX]
 [WAIT]
 [KILLLEADER]
 陳獨秀
 [KILLLEADER]
 鮑羅廷
 [GAINUNIT]
 共產黨/賀龍
 [UNITCLASS]
 賀龍/民兵
 [LEVELUP]
 賀龍/3
 [GAINUNIT]
 共產黨/劉伯承
 [CITYOWNER]
 南昌/共產黨
 [COMMANDER]
 共產黨/張國燾
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]101
 Name=廣州暴動
Condition
 [Event/=]南昌暴動
 ![CityOwner/共產黨]南昌
 [FactionExist/=]桂系
 [FactionExist/=]共產黨
Script
 [PLAYBGM]
 [PICTURE]
 E101a/廣州暴動1
 [TEXT]
 南昌暴動失敗後，中共仍依照共產國際的指示繼續在各地發動武裝暴動。此時國民政府中武漢政府方的張發奎依照汪精衛的指示發動政變，欲驅逐李濟深進而占領廣東。
 [TX]
 [WAIT]
 [TEXT]
 然而，張發奎的部隊葉劍英等人為潛伏共產黨員。中共遂趁張發奎在廣州發動政變混亂之際，發動暴動占領廣州城，並宣布成立政府。
 [TX]
 [WAIT]
 [PLAYBGM]
 [PICTURE]
 E101b/廣州暴動2
 [TEXT]
 中共為了報復先前在清黨所遭受的鎮壓，在廣州大肆搜殺，暴動軍甚至縱火焚城，廣州陷入火海，萬餘民房被燒毀。超過兩萬人死亡，其中大多數為被波及的市民。
 [TX]
 [WAIT]
 [TEXT]
 如此殘酷的暴行引起全國的譴責聲浪，國民政府宣布與蘇聯斷交，並驅逐各地的蘇聯僑民和關閉蘇聯領事館。指使張發奎政變的汪精衛也被認為須為此事負上間接責任，被迫下野。張發奎亦被迫離開廣東，將廣州交給桂系。
 [TX]
 [WAIT]
 [TEXT]
 震驚國際的廣州暴動結束了，而廣東在此事後成為了桂系的勢力範圍‧‧‧。
 [TX]
 [WAIT]
 [TEXT]
 [CITYOWNER]
 廣州/共產黨
 [CITYOWNER]
 汕頭/粵系
 [CITYOWNER]
 海南島/粵系
 [CITYOWNER]
 韶關/粵系
 [GAINUNIT]
 粵系/李濟琛
 [GAINUNIT]
 粵系/陳濟棠
 [GAINUNIT]
 粵系/陳銘樞
 [GAINUNIT]
 粵系/蔣光鼐
 [GAINUNIT]
 粵系/蔡廷鍇
 [SPPERCENT]
 廣州/50
 [REFORM]
 粵系/FreeMarket
 [REFORM]
 粵系/Capitalism
 [COMMANDER]
 粵系/李濟琛
 [UNITCLASS]
 陳銘樞/新軍步兵
 [UNITCLASS]
 蔣光鼐/新軍步兵
 [UNITCLASS]
 蔡廷鍇/新軍步兵
 [GAINMONEY]
 粵系/500
 [PEACEALL]
 粵系
 [WAR]
 共產黨/粵系
 [LEVELUP]
 陳銘樞/3
 [LEVELUP]
 蔣光鼐/3
 [LEVELUP]
 蔡廷鍇/3
 [CLEARAGENDA]
 粵系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]102
 Name=濟南慘案
Condition
 [CityOwner/國民政府]濟南
Script
 [QUESTION]
 如何面對日本挑釁？
 [TX]
 [ANSWER]
 歷史/暫不抵抗，繞道北伐
 假想/欺人太甚，全力反擊
 [ASK]
 國民政府/歷史
 [END]
 [LABEL]
 歷史
 [ALLPOLICE]
 國民政府/-50
 [END]
 [LABEL]
 假想
 [WAR]
 國民政府/大日本帝國
 [ALLPOLICE]
 國民政府/50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]103
 Name=下野宣言
Condition
 [Event/=]寧漢分裂
 ![CityOwner/奉系]徐州
 ![CityOwner/直魯聯軍]徐州
 [MasterOf/直魯聯軍]奉系
 [FactionExist/=]桂系
 [FactionExist/=]國民政府
Script
 [PLAYBGM]
 [PICTURE]
 E103a/國民政府
 [TEXT]
 國民政府南京方和武漢方的分裂，其名目為容共與否。然而在南京政府宣布清黨後，武漢方也繼而全面分共。雙方分裂的口實已不存在。
 [TX]
 [WAIT]
 [TEXT]
 然而，武漢方此時認為必須排除自立政府的蔣中正，寧漢雙方的復合才有可能，否則武漢方將大舉東進進攻南京。徐州之戰中，蔣遭到北洋軍的反擊而戰敗，一時更成為眾矢之的，蔣憤而處死前敵總指揮王天培。
 [TX]
 [WAIT]
 [PICTURE]
 E103b/李黃白
 [TEXT]
 此時原本與蔣中正合作清黨並建立南京政府的桂系，轉而傾向武漢方，桂軍對南京形成了包圍之勢，意圖掌握南京政府的實權而逼蔣下台。
 [TX]
 [WAIT]
 [PICTURE]
 E103c/蔣中正
 [TEXT]
 蔣中正陷於孤立，被迫辭去各職而下野。在內部角力、失去總司令的情況下，北伐戰局的情勢更為不明朗。
 [TX]
 [WAIT]
 [CITYOWNER]
 徐州/直魯聯軍
 [DISBAND]
 蔣中正
 [COMMANDER]
 國民政府/何應欽
 [ALLPOLICE]
 國民政府/-50
 [ALLLOYALITY]
 國民政府/-50
 [KILLLEADER]
 王天培
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]104
 Name=二次北伐
Condition
 [Event/=]下野宣言
 [Event/=]廣州暴動
Script
 [PLAYBGM]
 [PICTURE]
 E104c/桂湘粵黔
 [TEXT]
 北伐軍總司令蔣中正下野後，國民政府內部遍地烽火，既有共產黨接二連三掀起的武裝暴動，又有桂系、湘系、黔系、粵系相繼火拼不已‧‧‧。
 [TX]
 [WAIT]
 [PICTURE]
 E104a/蔣中正
 [TEXT]
 國民政府中反對蔣中正的人仍多，但此時已無人可代替蔣來收拾此殘局。在各地軍人亦紛電促蔣再起的大勢下，國民黨第二屆四中全會預備會議決議請蔣復職。
 [TX]
 [WAIT]
 [PICTURE]
 E104b/蔣中正
 [TEXT]
 在南京的四中全會中，蔣被推為軍事委員會委員長及復職為北伐軍總司令。
 [TX]
 [WAIT]
 [TEXT]
 蔣之復職代表原本陷入分裂的北伐軍再次有了領導人，一度因內部紛爭蒙上陰影的北伐，能否在蔣中正的帶領下盡其全功？
 [TX]
 [WAIT]
 [GAINUNIT]
 國民政府/蔣中正
 [COMMANDER]
 國民政府/蔣中正
 [UNITCLASS]
 蔣中正/黃埔步兵
 [LEVELUP]
 蔣中正/3
 [ALLLOYALITY]
 國民政府/50
 [ALLPOLICE]
 國民政府/50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]105
 Name=江東猛虎
Condition
 [Event/=]誓師北伐
 ![CityOwner/直系]武漢
 [AtWar/國民政府]直系
 [FactionExist/=]五省聯軍
Script
 [PLAYBGM]
 [TEXT]
 直系將領孫傳芳，人稱笑虎將軍。
 [TX]
 [WAIT]
 [TEXT]
 在二次直奉戰爭中，直系兵敗如山倒，其後直系在長江下游的地盤也遭到奉軍的進佔。但直系後起之秀孫傳芳反而在蘇皖一舉大破奉軍，得到東南直系諸將推載為五省聯軍總司令，其聲勢一時有凌駕於直系領袖吳佩孚之勢。
 [TX]
 [WAIT]
 [PICTURE]
 E105a/武昌北伐軍
 [TEXT]
 其後吳佩孚在華中復出，孫傳芳又再度必須受吳之節制，然而孫已有取而代之之心。北伐軍進攻湖北，吳佩孚接二連三向孫緊急求援，曾受吳提拔的孫傳芳卻只是虛應故事，擁兵坐看吳佩孚敗亡。
 [TX]
 [WAIT]
 [PICTURE]
 E105b/武昌北伐軍
 [TEXT]
 直至吳佩孚兵敗，武昌被圍，原本按兵不動已久的孫傳芳才對北伐軍宣戰，試圖在北伐軍和吳佩孚兩敗俱傷後坐收漁人之利。
 [TX]
 [WAIT]
 [PICTURE]
 E105c/武昌北伐軍
 [TEXT]
 北伐之初，蔣中正和孫傳芳都曾對對方做出中立保證，然而雙方均未把此種保證當真，吳佩孚既敗，早已暗中摩拳擦掌已久的蔣孫二人即欲一決雌雄。
 [TX]
 [WAIT]
 [PICTURE]
 E105d/孫蔣
 [TEXT]
 孫傳芳之大軍好整以暇的從江西和福建西進向北伐軍挑戰，席捲東南的直系新秀孫傳芳和新崛起的耀眼新星蔣中正，雙方之較量究竟鹿死誰手？
 [TX]
 [WAIT]
 [WAR]
 五省聯軍/國民政府
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]106
 Name=東北易幟
Condition
 [Event/=]皇姑屯事件
Script
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]107
 Name=霧社事件
Condition
 [Turn/=]69
 [CityOwner/大日本帝國]臺北
 [CityOwner/大日本帝國]高雄
Script
 [TEXT]
 清廷割台後，日本逐步深入清朝過往未能控制的台灣內地山區，並支配原住民部落與當地的林業資源
 [TX]
 [WAIT]
 [PICTURE]
 RocEvent107a/霧社事件1
 [TEXT]
 由於日本殖民政府的各種管制，原住民無法再以狩獵與織耕等傳統方式維持生計，被迫淪為遭日方層層剝削的勞工，生活困頓，倍受歧視。
 [TX]
 [WAIT]
 [PLAYBGM]
 [TEXT]
 在不堪日方長年的奴役和虐待後，馬赫坡社頭目莫那‧魯道終於決定率領族人起事反日。昭和五年１０月２７日，原住民對霧社警察分室、學校、郵局、官舍、學校展開攻擊，不分男女老幼的斬殺百餘名日本人。
 [TX]
 [WAIT]
 [PICTURE]
 RocEvent107b/霧社事件2
 [TEXT]
 遭此事震驚的日本台灣總督隨即下令緊急調派駐台各地之日軍，出動包含臺灣軍司令部、守備隊司令部、臺北步兵第一聯隊等軍警逾２５００名進攻霧社，原住民隨即退入深山持續抵抗。
 [TX]
 [WAIT]
 [TEXT]
 面對據守天險且多數為婦孺的千餘原住民，日軍動用了大炮、空軍與毒氣彈進行攻擊，在壓倒性的武力差距下，原住民死傷慘重，不願投降者與眷屬紛紛自縊
 [TX]
 [WAIT]
 [PICTURE]
 RocEvent107c/霧社事件3
 [TEXT]
 在起事之領導者皆身亡後，殘餘之原住民婦孺向日軍投降，卻仍遭到報復，參與起事之部落生還者幾乎在收容所中被屠殺殆盡
 [TX]
 [WAIT]
 [TEXT]
 日本治台以來最大一次的原住民抗日事件就此落幕，為了追求尊嚴，參與起事的部落付出了幾乎全族盡滅的代價，然而仍未能動搖日本的統治‧‧‧
 [TX]
 [WAIT]
 [KILLLEADER]
 莫那魯道
 [POLICEPERCENT]
 臺北/50
 [POLICEPERCENT]
 高雄/50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]108
 Name=九一八事變
Condition
Script
[/SCRIPTEVENT]
[SCRIPTEVENT]109
 Name=中華蘇維埃共和國成立
Condition
 [Event/=]南昌暴動
 [FactionCityMore/共產黨]3
Script
 [PLAYBGM]
 [TEXT]
 清黨後，中共開始建立自己的武力與根據地，並趁國民政府內鬥之際不斷擴大勢力。
 [TX]
 [WAIT]
 [PICTURE]
 E106a/中華蘇維埃
 [TEXT]
 在共產國際欲於中國建立紅色政權的政策下，中共召開中華蘇維埃第一次全國代表大會，宣告中華蘇維埃共和國成立。然而除了蘇聯外，國際上無他國予以承認。
 [TX]
 [WAIT]
 [TEXT]
 毛澤東、項英、張國燾聯名於《中華蘇維埃共和國中央執行委員會布告》清楚表明在一個中國疆域內有兩國：「從現在起，中國疆域內有不同的兩國，一個是中華民國，‧‧‧，一是中華蘇維埃共和國，‧‧‧」並支持蘇聯推動的的蒙獨、疆獨政策。
 [TX]
 [WAIT]
 [PICTURE]
 E106b/中華蘇維埃
 [TEXT]
 然而在共產國際扶植下成立的中華蘇維埃共和國，必須接受共產國際的強勢領導。中華蘇維埃喊出了「武裝保衛蘇聯」的口號，以王明為代表的國際派在共產國際的幫助下實際取得了領導權，在共產國際的批准下，博古出任中國共產黨中央委員會總書記，成為了中共最高領導人。
 [TX]
 [WAIT]
 [TEXT]
 民國以來，中國雖多內戰，然而均是同在民國旗號下之爭。如今在蘇聯的輸出革命政策下，中共建立了民國第一個分離主義割據政權。
 [TX]
 [WAIT]
 [KILLLEADER]
 葉挺
 [GAINUNIT]
 共產黨/秦邦憲
 [COMMANDER]
 共產黨/秦邦憲
 [UNITCLASS]
 秦邦憲/內閣
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]110
 Name=遵義會議
Condition
 [Event/=]中華蘇維埃共和國成立
 ![FactionCityMore/共產黨]1
Script
 [PLAYBGM]
 [PICTURE]
 E110a/長征
 [TEXT]
 中共在不斷擴大根據地後成立了中華蘇維埃共和國，然而在遭到強力圍剿下下，中共喪師失地，被迫放棄根據地展開流亡。
 [TX]
 [WAIT]
 [TEXT]
 面對慘重失敗，中共內部出現了對國際派領導不滿的聲浪。中共中央政治局的一次擴大會議上，毛澤東被增選為中共中央政治局常委，恢復了對紅軍的指揮權。
 [TX]
 [WAIT]
 [PICTURE]
 E110b/長征
 [TEXT]
 在一度被排斥於黨和紅軍的領導之外後，毛澤東再度進入了中共的領導核心，他將帶領中共走向什麼道路呢‧‧‧？
 [TX]
 [WAIT]
 [DISBAND]
 秦邦憲
 [GAINUNIT]
 共產黨/毛澤東
 [COMMANDER]
 共產黨/毛澤東
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]111
 Name=中德合作（二）
Condition
Script
[/SCRIPTEVENT]
[SCRIPTEVENT]112
 Name=中德合作（三）
Condition
Script
[/SCRIPTEVENT]
[SCRIPTEVENT]113
 Name=富田事變
Condition
 [Event/=]南昌暴動
 [CityOwner/共產黨]贛州
Script
 [PLAYBGM]
 [TEXT]
 北伐中，蔣中正曾在江西試圖成立名為AB團的反共組織，以對抗在國民政府中逐漸坐大的共產黨，然而此組織僅存在三個月就遭到中共的暴動破壞，還未來得及參加清黨即解體。
 [TX]
 [WAIT]
 [PICTURE]
 E113a/AB團
 [TEXT]
 然而此時在江西建立根據地的毛澤東發動了AB團肅反運動，以內部有AB團滲透之名，大量黨員、士兵被冠以AB團之名遭捕殺。紅二十軍爆發反抗毛澤東濫捕的兵變。
 [TX]
 [WAIT]
 [TEXT]
 紅二十軍很快就遭到鎮壓，副排長級以上的軍官全被中共處死，紅二十軍番號被取消。此事後中共的肅反運動進入高潮，至少有數千幹部、軍官被害，江西蘇區陷入了紅色恐怖‧‧‧。
 [TX]
 [WAIT]
 [ALLWEAKEN]
 共產黨
 [ALLPOLICE]
 共產黨/50
 [ALLLOYALITY]
 共產黨/50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]114
 Name=玉帥南征
Condition
 [Event/=]誓師北伐
 ![FactionExist/=]湘系
 [FactionExist/=]五省聯軍
 [CityOwner/直系]長沙
 [CityOwner/直系]衡陽
Script
 [PLAYBGM]
 [TEXT]
 在二次直奉戰爭中，直系兵敗如山倒，其後直系在長江下游的地盤也遭到奉軍的進佔。但直系後起之秀孫傳芳反而在蘇皖一舉大破奉軍，得到東南諸將推載為五省聯軍總司令，其聲勢一時有凌駕於直系領袖吳佩孚之勢。
 [TX]
 [WAIT]
 [PICTURE]
 E114a/玉帥
 [TEXT]
 然而，復出的吳佩孚在圍攻國民軍的戰威中聲威再振，又藉由干涉湖南取得了華中的控制權。在此情勢下，居於下游且身為直系部將的孫傳芳無法再對吳陽奉陰違。
 [TX]
 [WAIT]
 [TEXT]
 於是，長江中下游均統一在直系的旗幟下，這會是吳佩孚所領導之直系再興的契機嗎？
 [TX]
 [WAIT]
 [MASTER]
 直系/五省聯軍
 [ALLLOYALITY]
 直系/50
 [ALLPOLICE]
 直系/50
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]115
 Name=東北軍入關
Condition
Script
[/SCRIPTEVENT]
[SCRIPTEVENT]116
 Name=太原誓師
Condition
 [AtWar/奉系]國民政府
 ![Event/=]皇姑屯事件
 ![CityOwner/奉系]徐州
 ![CityOwner/奉系]南京
 ![CityOwner/奉系]上海
 ![CityOwner/直魯聯軍]徐州
 ![CityOwner/直魯聯軍]南京
 ![CityOwner/直魯聯軍]上海
 [FactionExist/=]晉系
Script
 [PLAYBGM]
 [PICTURE]
 E116a/閻孫
 [TEXT]
 晉系領袖閻錫山，曾為同盟會會員並參加辛亥革命。其任山西都督後，在多次軍閥混戰中始終屹立不搖。
 [TX]
 [WAIT]
 [TEXT]
 北洋政府在由袁世凱、皖系、直系、奉系統治期間，閻錫山都曾為其作戰，並在戰局有變時迅速倒戈至較有利之一方，因此儘管北方混戰不已，閻錫山卻能穩坐山西。
 [TX]
 [WAIT]
 [PICTURE]
 E116b/晉軍
 [TEXT]
 在直奉同盟之際，閻錫山也加入了對國民軍的圍攻。但北伐開始後，閻錫山感到勢逐漸變化為對北伐軍有利。於是藉由從前與同盟會的關係，從奉軍一方搖身一變為國民革命軍第三集團軍司令，轉而與馮玉祥並肩對奉軍作戰。
 [TX]
 [WAIT]
 [TEXT]
 閻錫山在太原宣示加入北伐使得北方局勢丕變，在奉系獨木難支的情況下北洋政府將走向什麼樣的命運呢‧‧‧？
 [TX]
 [WAIT]
 [CITYOWNER]
 太原/晉系
 [PEACEALL]
 晉系
 [WAR]
 晉系/奉系
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]117
 Name=湘南暴動
Condition
Script
[/SCRIPTEVENT]
[SCRIPTEVENT]118
 Name=安國軍成立
Condition
 ![FactionCityMore/五省聯軍]5
 [AtWar/五省聯軍]國民政府
 ![AtWar/五省聯軍]奉系
 ![Event/=]皇姑屯事件
 [FactionExist/=]奉系
 [FactionExist/=]五省聯軍
 ![MasterOf/五省聯軍]直系
 [MasterOf/直魯聯軍]奉系
Script
 [PLAYBGM]
 [PICTURE]
 E118a/孫傳芳
 [TEXT]
 反奉戰爭中，孫傳芳曾率直軍痛擊入侵長江流域的奉軍，予以大破之，使奉軍損失慘重。
 [TX]
 [WAIT]
 [TEXT]
 然而在孫傳芳遭到北伐軍大敗而走投無路之際，竟轉而向年前剛被自己狠搧一記大耳光的張作霖乞援。孫既能屈能伸，張作霖竟也大度能容，不僅保留孫傳芳五省聯軍總司令的頭銜，又成立安國軍，自任總司令並任孫為副司令。
 [TX]
 [WAIT]
 [PICTURE]
 E118b/安國軍
 [TEXT]
 其後，張作霖在北京成立安國軍政府，以中華民國安國陸海軍大元帥身份行使大總統職權，並重組北京政府為清一色的奉系內閣。張作霖成為袁世凱後北洋政府以來第一個主覽軍、政大權的元首。
 [TX]
 [WAIT]
 [PICTURE]
 E118c/張作霖
 [TEXT]
 北洋集團自從袁世凱死後歷經了十年混戰，終於又出現登峰造極的領袖，但此時是否為時已晚‧‧‧？
 [TX]
 [WAIT]
 [WAR]
 國民政府/奉系
 [MASTER]
 奉系/五省聯軍
 [END]
[/SCRIPTEVENT]
[SCRIPTEVENT]119
 Name=中東路事件
Condition
Script
[/SCRIPTEVENT]

`;

// 将数据分割成每一行
const lines = data_str.trim().split('\n');

// 创建一个空数组来保存有效行
const valid_lines = [];

// 遍历每一行，判断是否满足要求，将有效行添加到数组中
lines.forEach(line => {
  //if (!line.startsWith('L=[') && !line.includes('.mp3') && line.trim() !== '') {
  if (!line.startsWith(' [TX') && !line.startsWith(' [WAIT') && !line.startsWith(' [TEXT') && !line.startsWith(' [PLAYBGM') && !line.startsWith(' [PICTURE') && !line.includes('.mp3') && line.trim() !== '') {
    valid_lines.push(line.replace('L=', ''));
  }
});

// 打印有效行
console.log(JSON.stringify(valid_lines));

    }
    update() { }
}

var config = {
    type: Phaser.AUTO,
    parent: 'game',
    width: 800,
    height: 600,
    scene: Test
};

var game = new Phaser.Game(config);